### ISSUE TITLE
Application  Error

### ISSUE THREAD

**Issue by mirlife** [Shubhamai/plant-disease-detection#5]
it has error

**Comment by Shubhamai** [comment]
What error you are getting ?

**Comment by muhamadnss** [comment]
Hello, thanks for your great app
But I had an error while trying to install requirement, the error message I got is :

`   ERROR: Command errored out with exit status 1:
     command: 'e:\learn\python\leafdiseasedetection\envleaf\scripts\python.exe' 'e:\learn\python\leafdiseasedetection\envleaf\lib\site-packages\pip\_vendor\pep517\_in_process.py' prepare_metadata_for_build_wheel 'C:\Users\LENOVO~1\AppData\Local\Temp\tmp5lbqdohq'
         cwd: C:\Users\Lenovo T410\AppData\Local\Temp\pip-install-93x8ky74\numpy
    Complete output (187 lines):
    Running from numpy source directory.
    setup.py:461: UserWarning: Unrecognized setuptools command, proceeding with generating Cython sources and expanding templates
      run_build = parse_setuppy_commands()
    Processing numpy/random\_bounded_integers.pxd.in
    Processing numpy/random\mtrand.pyx
    Processing numpy/random\_bit_generator.pyx
    Processing numpy/random\_bounded_integers.pyx.in
    Processing numpy/random\_common.pyx
    Processing numpy/random\_generator.pyx
    Processing numpy/random\_mt19937.pyx
    Processing numpy/random\_pcg64.pyx
    Processing numpy/random\_philox.pyx
    Processing numpy/random\_sfc64.pyx
    Cythonizing sources
    blas_opt_info:
    blas_mkl_info:
    No module named 'numpy.distutils._msvccompiler' in numpy.distutils; trying from distutils
    customize MSVCCompiler
      libraries mkl_rt not found in ['e:\\learn\\python\\leafdiseasedetection\\envleaf\\lib', 'C:\\']
      NOT AVAILABLE
''
    blis_info:
      libraries blis not found in ['e:\\learn\\python\\leafdiseasedetection\\envleaf\\lib', 'C:\\']
      NOT AVAILABLE

    openblas_info:
      libraries openblas not found in ['e:\\learn\\python\\leafdiseasedetection\\envleaf\\lib', 'C:\\']
    get_default_fcompiler: matching types: '['gnu', 'intelv', 'absoft', 'compaqv', 'intelev', 'gnu95', 'g95', 'intelvem', 'intelem', 'flang']'
    customize GnuFCompiler
    Could not locate executable g77
    Could not locate executable f77
    customize IntelVisualFCompiler
    Could not locate executable ifort
    Could not locate executable ifl
    customize AbsoftFCompiler
    Could not locate executable f90
    customize CompaqVisualFCompiler
    Could not locate executable DF
    customize IntelItaniumVisualFCompiler
    Could not locate executable efl
    customize Gnu95FCompiler
    Could not locate executable gfortran
    Could not locate executable f95
    customize G95FCompiler
    Could not locate executable g95
    customize IntelEM64VisualFCompiler
    customize IntelEM64TFCompiler
    Could not locate executable efort
    Could not locate executable efc
    customize PGroupFlangCompiler
    Could not locate executable flang
    don't know how to compile Fortran code on platform 'nt'
      NOT AVAILABLE

    atlas_3_10_blas_threads_info:
    Setting PTATLAS=ATLAS
      libraries tatlas not found in ['e:\\learn\\python\\leafdiseasedetection\\envleaf\\lib', 'C:\\']
      NOT AVAILABLE

    atlas_3_10_blas_info:
      libraries satlas not found in ['e:\\learn\\python\\leafdiseasedetection\\envleaf\\lib', 'C:\\']
      NOT AVAILABLE

    atlas_blas_threads_info:
    Setting PTATLAS=ATLAS
      libraries ptf77blas,ptcblas,atlas not found in ['e:\\learn\\python\\leafdiseasedetection\\envleaf\\lib', 'C:\\']
      NOT AVAILABLE

    atlas_blas_info:
      libraries f77blas,cblas,atlas not found in ['e:\\learn\\python\\leafdiseasedetection\\envleaf\\lib', 'C:\\']
      NOT AVAILABLE

    accelerate_info:
      NOT AVAILABLE

    C:\Users\Lenovo T410\AppData\Local\Temp\pip-install-93x8ky74\numpy\numpy\distutils\system_info.py:1896: UserWarning:
        Optimized (vendor) Blas libraries are not found.
        Falls back to netlib Blas library which has worse performance.
        A better performance should be easily gained by switching
        Blas library.
      if self._calc_info(blas):
    blas_info:
      libraries blas not found in ['e:\\learn\\python\\leafdiseasedetection\\envleaf\\lib', 'C:\\']
      NOT AVAILABLE

    C:\Users\Lenovo T410\AppData\Local\Temp\pip-install-93x8ky74\numpy\numpy\distutils\system_info.py:1896: UserWarning:
        Blas (http://www.netlib.org/blas/) libraries not found.
        Directories to search for the libraries can be specified in the
        numpy/distutils/site.cfg file (section [blas]) or by setting
        the BLAS environment variable.
      if self._calc_info(blas):
    blas_src_info:
      NOT AVAILABLE

    C:\Users\Lenovo T410\AppData\Local\Temp\pip-install-93x8ky74\numpy\numpy\distutils\system_info.py:1896: UserWarning:
        Blas (http://www.netlib.org/blas/) sources not found.
        Directories to search for the sources can be specified in the
        numpy/distutils/site.cfg file (section [blas_src]) or by setting
        the BLAS_SRC environment variable.
      if self._calc_info(blas):
      NOT AVAILABLE

    non-existing path in 'numpy\\distutils': 'site.cfg'
    lapack_opt_info:
    lapack_mkl_info:
      libraries mkl_rt not found in ['e:\\learn\\python\\leafdiseasedetection\\envleaf\\lib', 'C:\\']
      NOT AVAILABLE

    openblas_lapack_info:
      libraries openblas not found in ['e:\\learn\\python\\leafdiseasedetection\\envleaf\\lib', 'C:\\']
      NOT AVAILABLE

    openblas_clapack_info:
      libraries openblas,lapack not found in ['e:\\learn\\python\\leafdiseasedetection\\envleaf\\lib', 'C:\\']
      NOT AVAILABLE

    flame_info:
      libraries flame not found in ['e:\\learn\\python\\leafdiseasedetection\\envleaf\\lib', 'C:\\']
      NOT AVAILABLE

    atlas_3_10_threads_info:
    Setting PTATLAS=ATLAS
      libraries lapack_atlas not found in e:\learn\python\leafdiseasedetection\envleaf\lib
      libraries tatlas,tatlas not found in e:\learn\python\leafdiseasedetection\envleaf\lib
      libraries lapack_atlas not found in C:\
      libraries tatlas,tatlas not found in C:\
    <class 'numpy.distutils.system_info.atlas_3_10_threads_info'>
      NOT AVAILABLE

    atlas_3_10_info:
      libraries lapack_atlas not found in e:\learn\python\leafdiseasedetection\envleaf\lib
      libraries satlas,satlas not found in e:\learn\python\leafdiseasedetection\envleaf\lib
      libraries lapack_atlas not found in C:\
      libraries satlas,satlas not found in C:\
    <class 'numpy.distutils.system_info.atlas_3_10_info'>
      NOT AVAILABLE

    atlas_threads_info:
    Setting PTATLAS=ATLAS
      libraries lapack_atlas not found in e:\learn\python\leafdiseasedetection\envleaf\lib
      libraries ptf77blas,ptcblas,atlas not found in e:\learn\python\leafdiseasedetection\envleaf\lib
      libraries lapack_atlas not found in C:\
      libraries ptf77blas,ptcblas,atlas not found in C:\
    <class 'numpy.distutils.system_info.atlas_threads_info'>
      NOT AVAILABLE

    atlas_info:
      libraries lapack_atlas not found in e:\learn\python\leafdiseasedetection\envleaf\lib
      libraries f77blas,cblas,atlas not found in e:\learn\python\leafdiseasedetection\envleaf\lib
      libraries lapack_atlas not found in C:\
      libraries f77blas,cblas,atlas not found in C:\
    <class 'numpy.distutils.system_info.atlas_info'>
      NOT AVAILABLE

    lapack_info:
      libraries lapack not found in ['e:\\learn\\python\\leafdiseasedetection\\envleaf\\lib', 'C:\\']
      NOT AVAILABLE

    C:\Users\Lenovo T410\AppData\Local\Temp\pip-install-93x8ky74\numpy\numpy\distutils\system_info.py:1730: UserWarning:
        Lapack (http://www.netlib.org/lapack/) libraries not found.
        Directories to search for the libraries can be specified in the
        numpy/distutils/site.cfg file (section [lapack]) or by setting
        the LAPACK environment variable.
      return getattr(self, '_calc_info_{}'.format(name))()
    lapack_src_info:
      NOT AVAILABLE

    C:\Users\Lenovo T410\AppData\Local\Temp\pip-install-93x8ky74\numpy\numpy\distutils\system_info.py:1730: UserWarning:
        Lapack (http://www.netlib.org/lapack/) sources not found.
        Directories to search for the sources can be specified in the
        numpy/distutils/site.cfg file (section [lapack_src]) or by setting
        the LAPACK_SRC environment variable.
      return getattr(self, '_calc_info_{}'.format(name))()
      NOT AVAILABLE

    C:\Users\Lenovo T410\AppData\Local\Programs\Python\Python39\lib\distutils\dist.py:274: UserWarning: Unknown distribution option: 'define_macros'
      warnings.warn(msg)
    running dist_info
    running build_src
    build_src
    building py_modules sources
    creating build
    creating build\src.win-amd64-3.9
    creating build\src.win-amd64-3.9\numpy
    creating build\src.win-amd64-3.9\numpy\distutils
    building library "npymath" sources
    error: Microsoft Visual C++ 14.0 or greater is required. Get it with "Microsoft C++ Build Tools": https://visualstudio.microsoft.com/visual-cpp-build-tools/
    ----------------------------------------
ERROR: Command errored out with exit status 1: 'e:\learn\python\leafdiseasedetection\envleaf\scripts\python.exe' 'e:\learn\python\leafdiseasedetection\envleaf\lib\site-packages\pip\_vendor\pep517\_in_process.py' prepare_metadata_for_build_wheel 'C:\Users\LENOVO~1\AppData\Local\Temp\tmp5lbqdohq' Check the logs for full command output.`

**Comment by Shubhamai** [comment]
As said in the error `Microsoft Visual C++ 14.0 or greater is required. Get it with "Microsoft C++ Build Tools": https://visualstudio.microsoft.com/visual-cpp-build-tools/` , you need to install Microsoft C++ Build Tools which you can install from the given link :)

**Comment by muhamadnss** [comment]
Hello again :)

During the installation process (I use python 3.6.5 in Conda environment), I encountered several problems, one of which was the irrelevance of the tensorflow 2.4.0 version with the existing tensorboard and tensorflow-estimator versions. So I downgraded the tensorflow version to 2.0.3 then used the tensorboard version 2.0.0 and the tensorflow-estimator version 2.0.0 and finnaly, installation process was running properly

But when the application deployment process to http://localhost:8501 using streamlit, I encountered an error :

`ImportError: Traceback (most recent call last): File "e:\learn\plantdiseasedetection\venv\lib\site-packages\tensorflow_core\python\pywrap_tensorflow.py", line 58, in <module> from tensorflow.python.pywrap_tensorflow_internal import * File "e:\learn\plantdiseasedetection\venv\lib\site-packages\tensorflow_core\python\pywrap_tensorflow_internal.py", line 28, in <module> _pywrap_tensorflow_internal = swig_import_helper() File "e:\learn\plantdiseasedetection\venv\lib\site-packages\tensorflow_core\python\pywrap_tensorflow_internal.py", line 24, in swig_import_helper _mod = imp.load_module('_pywrap_tensorflow_internal', fp, pathname, description) File "C:\Users\Lenovo T410\Anaconda3\lib\imp.py", line 243, in load_module return load_dynamic(name, filename, file) File "C:\Users\Lenovo T410\Anaconda3\lib\imp.py", line 343, in load_dynamic return _load(spec) ImportError: DLL load failed: A dynamic link library (DLL) initialization routine failed. Failed to load the native TensorFlow runtime. See https://www.tensorflow.org/install/errors for some common reasons and solutions. Include the entire stack trace above this error message when asking for help. `

I am quite confused of an error, so do you recognize this error ?

Thank in advance,

**Comment by Shubhamai** [comment]
`DLL load failed` is one of those errors that really sucks. I forgot how I actually solved the issue, but try reinstalling the Anaconda itself, maybe it will help.

**Comment by muhamadnss** [comment]
Thanks for your great and fast response, I'll try it immediately 👍 
By the way, thank you for replying my email too

**Comment by Shubhamai** [comment]
:)
